version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: development
    groups:
      deps:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: development
    groups:
      action-deps:
        applies-to: version-updates
        patterns:
          - "*"
