name: tests
on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: vet
      run: go vet ./...
    - name: test
      run: go test -v ./...
