name: tests
on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: vet
        run: go vet ./...
      - name: test
        run: go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...
      - name: codecov
        run: bash <(curl -s  https://codecov.io/bash)
